INSERT INTO users (name, age) VALUES ('Max', 20); 
INSERT INTO users (name, age) VALUES ('Adam', 45);
INSERT INTO users (name, age) VALUES ('Daniel', 29);
INSERT INTO users (name, age) VALUES ('Matt', 41);
INSERT INTO users (name, age) VALUES ('Carol', 34);
INSERT INTO users (name, age) VALUES ('Nia', 36);
INSERT INTO users (name, age) VALUES ('Bob', 55);
INSERT INTO users (name, age) VALUES ('Judy', 37);
INSERT INTO users (name, age) VALUES ('Dan', 33);
INSERT INTO users (name, age) VALUES ('Kat', 19);
INSERT INTO users (name, age) VALUES ('Ron', 25);
INSERT INTO users (name, age) VALUES ('Missy', 43);
INSERT INTO users (name, age) VALUES ('Jake', 28);
INSERT INTO users (name, age) VALUES ('Hannah', 29);
INSERT INTO users (name, age) VALUES ('Laura', 23);
INSERT INTO users (name, age) VALUES ('Avi', 33);
INSERT INTO users (name, age) VALUES ('Alex', 77);
INSERT INTO users (name, age) VALUES ('Mia', 65);
INSERT INTO users (name, age) VALUES ('Sam', 28);
INSERT INTO users (name, age) VALUES ('Ben', 45);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('AxleHire', 'Delivery', 2000.00, '2020-01-01', '2021-01-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Deliveroo', 'Delivery', 5000.00, '2020-10-01', '2021-07-20');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Amazon Fast', 'Delivery', 3000.00, '2020-05-01', '2020-07-15');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Counter', 'Tech', 20000.00, '2020-01-01', '2021-08-30');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Max', 'Tech', 15000.00, '2020-03-15', '2021-08-10');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project2', 'Tech', 22000.00, '2020-01-01', '2021-11-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project3', 'Tech', 35000.00, '2020-11-01', '2022-01-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project5', 'Tech', 50000.00, '2020-07-01', '2021-12-31');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project4', 'Retail', 1100.00, '2020-05-01', '2021-12-01');
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('Project6', 'Tech', 212000.00, '2020-02-01', '2021-11-01');
INSERT INTO pledges (amount, user_id, project_id ) VALUES (50, 1, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (100, 2, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (150, 1, 2);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (250, 3, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (550, 4, 3);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (530, 5, 4);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (510, 6, 7);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (150, 7, 8);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (40, 8, 9);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (510, 9, 10);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (550, 10, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (510, 11, 4);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (80, 12, 10);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (11150, 13, 10);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (550, 14, 9);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (20, 15, 1);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (2550, 16, 8);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (50, 17, 8);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (505, 18, 9);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (150, 19, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (550, 20, 5);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (85, 20, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (520, 5, 7);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (50, 19, 4);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (150, 18, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (50, 1, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (560, 1, 7);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (505, 17, 6);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (50, 16, 8);
INSERT INTO pledges (amount, user_id, project_id ) VALUES (240, 15, 8);